{
  "formatVersion": "1.1",
  "component": {
    "group": "io.itsusinn.pkg",
    "module": "plugin",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.2.1.jar",
          "url": "plugin-1.2.1.jar",
          "size": 35094,
          "sha512": "50db6b56f961b4555687592602bce9561d3c4a4e45571b0d56957f0cf91732a7d47349a8b5136c74f9e7db1d1129fcd7c506f7edba26fab6eaea85969918c3ca",
          "sha256": "ab33c7d404081ad73aa57e0ea108ad31e78f88ec324946d31f5e6641c15c0d08",
          "sha1": "cc96e1310f68d15571f7138252c174ff2b0df335",
          "md5": "d1830f70fc06d0aa8cac679a8b10e4b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.2.1.jar",
          "url": "plugin-1.2.1.jar",
          "size": 35094,
          "sha512": "50db6b56f961b4555687592602bce9561d3c4a4e45571b0d56957f0cf91732a7d47349a8b5136c74f9e7db1d1129fcd7c506f7edba26fab6eaea85969918c3ca",
          "sha256": "ab33c7d404081ad73aa57e0ea108ad31e78f88ec324946d31f5e6641c15c0d08",
          "sha1": "cc96e1310f68d15571f7138252c174ff2b0df335",
          "md5": "d1830f70fc06d0aa8cac679a8b10e4b6"
        }
      ]
    }
  ]
}
